// 실제 Supabase DB 테이블명 매핑
// hospitals: 접두사 없음, crm_*: 별도 관리, 나머지: sales_ 또는 scv_ 접두사
export const T = {
  hospitals: 'hospitals',
  products: 'sales_products',
  leads: 'sales_leads',
  lead_activities: 'sales_lead_activities',
  emails: 'sales_emails',
  email_events: 'sales_email_events',
  email_sequences: 'sales_email_sequences',
  email_sequence_steps: 'sales_email_sequence_steps',
  demos: 'sales_demos',
  demo_evaluations: 'sales_demo_evaluations',
  scoring_results: 'sales_scoring_results',
  scoring_weights: 'sales_scoring_weights',
  scoring_change_history: 'sales_scoring_change_history',
  hospital_equipments: 'sales_hospital_equipments',
  hospital_treatments: 'sales_hospital_treatments',
  hospital_profiles: 'sales_hospital_profiles',
  hospital_doctors: 'sales_hospital_doctors',
  hospital_pricing: 'sales_hospital_pricing',
  hospital_events: 'sales_hospital_events',
  product_match_scores: 'sales_product_match_scores',
  kakao_messages: 'sales_kakao_messages',
  unsubscribes: 'sales_unsubscribes',
  api_usage_logs: 'sales_api_usage_logs',
  networks: 'sales_networks',
  network_branches: 'sales_network_branches',
  network_verification_logs: 'sales_network_verification_logs',
  signals: 'sales_signals',
  equipment_changes: 'sales_equipment_changes',
  system_settings: 'sales_system_settings',
  commissions: 'sales_commissions',
  crawl_snapshots: 'scv_crawl_snapshots',
  // v4.0 — 페르소나 / 시나리오 / 학습루프
  personas: 'sales_personas',
  insight_cards: 'sales_insight_cards',
  scenarios: 'sales_scenarios',
  buying_stages: 'sales_buying_stages',
  negative_notes: 'sales_negative_notes',
  rules: 'sales_rules',
  regional_clusters: 'sales_regional_clusters',
  franchise_networks: 'sales_franchise_networks',
  // 콜드메일 파이프라인
  email_campaigns: 'sales_email_campaigns',
  campaign_emails: 'sales_campaign_emails',
} as const;
